import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Marquee from "@/Components/Marquee";

const  NotoSerifBengali =  Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${NotoSerifBengali.className} h-full antialiased max-w`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <Marquee></Marquee>
        {children}
        </body>
    </html>
  );
}
